name: blbiLogin
version: '${version}'
main: com.blbilink.blbilogin.BlbiLogin
api-version: '1.20'
folia-supported: true
depend:
  - blbiLibrary
commands:
  login:
    description: "Login command"
    usage: /login <password>
    aliases: [l]
  register:
    description: "Register command"
    usage: /register <password>
    aliases: [reg]
  blbilogin:
    description: "Main plugin command"
    usage: /blbilogin <args>
  resetpassword:
    description: "Reset password"
    aliases:
      - resetpasswd
      - resetpass
      - resetpw
  kill:
    description: "Kill yourself"
    aliases:
      - suicide
  worldstats:
    description: "Show world statistics"
  info:
    description: "Show player and server info"
  stats:
    description: "Alias of worldstats"
  dupe:
    description: "Explains the chest boat dupe"
    usage: /dupe
  tpa:
    description: "Request to teleport to another player"
    usage: /tpa <player>
  tphere:
    description: "Request another player to teleport to you"
    usage: /tphere <player>
  tpaccept:
    description: "Accept a teleport request"
    usage: /tpaccept
  tpacancel:
    description: "Cancel teleport requests"
    usage: /tpacancel
  joindate:
    description: "Show when a player first joined"
    aliases: [jd]
  playtime:
    description: "Show a player's playtime"
    aliases: [pt]
  listplayers:
    description: "List registered usernames"
    usage: /listplayers <page>
  tpoffline:
    description: "Teleport to last logout location of a player"
    usage: /tpoffline <username>
  blacklist:
    description: "Blacklist a player from login"
    usage: /blacklist <username>
