name: blbiLogin
version: '${version}'
main: com.blbilink.blbilogin.BlbiLogin
api-version: '1.20'
folia-supported: true
depend:
  - blbiLibrary
commands:
  login:
    description: "Login command"
    usage: /login <password>
    aliases: [l]
  register:
    description: "Register command"
    usage: /register <password>
    aliases: [reg]
  blbilogin:
    description: "Main plugin command"
    usage: /blbilogin <args>
  resetpassword:
    description: "Reset password"
    aliases:
      - resetpasswd
      - resetpass
      - resetpw
  kill:
    description: "Kill yourself"
    aliases:
      - suicide
  vanish:
    description: "Toggle vanish mode"
    permission: blbilogin.vanish
  joinstats:
    description: "Show join statistics"
  worldstats:
    description: "Show world statistics"
  info:
    description: "Alias of worldstats"
  dupe:
    description: "Explains the chest boat dupe"
    usage: /dupe
  tpa:
    description: "Request to teleport to another player"
    usage: /tpa <player>
  tphere:
    description: "Request another player to teleport to you"
    usage: /tphere <player>
  tpaccept:
    description: "Accept a teleport request"
    usage: /tpaccept
